### ISSUE TITLE
Problem with casting higher level spells.

### ISSUE THREAD

**Issue by Nedrapter** [Moerill/Mess#114]
I'm casting Inflict wounds as level 1 spell (default), everything works fine. I get the 2 cards in chat, one with the description of spell and the clickacle "Attack" button, and the 2nd card with the 2 rolls (to Hit and Damage). All works perfect here.
When I'm choosing to cast it as level 2 though, I get only the 1st card. It has the clickable "Attack" button, which does nothing if clicked. The 2nd card with the "to Hit" and "Damage" rolls does not show. I've tried different characters, spells, refreshed etc. Deactivating the "Alternative Rolling and Targeting" option of the mod, make it work, but you don't get the super cool attack cards...
Is it a bug, or have I set up something wrong?

**Comment by ZenobiaTal** [comment]
Foundry version 0.7.8
Mess version 0.12.3
This issue is still present. Spell casting does not work at all when cast at higher levels, in order to get the base foundry rolls working again the alternative rolling and targetting 'activate' option has to be unselected, otherwise rolling at higher levels will not function at all.

**Comment by Moerill** [comment]
This won't be fixed, only update for mess that will be coming (regarding rolling issues) is removing them.
My replacement is now submitted and waits for approval. Meanwhile you can download the module and look at its features from its repository:
https://github.com/Moerill/fvtt-mars-5e
Manifest: https://raw.githubusercontent.com/Moerill/fvtt-mars-5e/master/module.json
