### ISSUE TITLE
Animations stop after approx one second if using with Haste module

### ISSUE THREAD

**Issue by Ironxxx** [Moerill/Mess#13]
Token Mold version 2.6
FVTT version 5.7
Browser and OS used. Or if the app itself is used. WIN 10 Chrome
Template Animations stop after approx one second if using with Haste module. It works fine otherwise. If you click anywhere in Foundry the animation starts again and stops after one second.
Console errors? (F12 or F11 in most browsers) None
Workflow to recreate the bug - Install Haste, Install MESS, create animated template from WEBM or MP4

**Comment by Moerill** [comment]
Thanks for the report, but i won't fix that one, for multiple reasons:
1. Haste is used to improve performance, propably because one needs it. Using video textures is the opposite: it worsens performance for gain of fidelity.
2. I stated in the [README](https://github.com/Moerill/Mess#module-compatiblity) that module conflicts may arise and that i do not really care about it for most parts.
