### ISSUE TITLE
Issue with using saved templates for spells and abilities

### ISSUE THREAD

**Issue by Deathtone3** [Moerill/Mess#61]
I seem to have an issue where I can't use my saved templates for spells and abilities.  Based on the documentation at this link https://github.com/Moerill/mess#ability-template-textures
I should be able to just right click and assign the ability one of my preset templates.  I don't get that menu for some reason.  I have removed the module and reinstalled it, and turned off all settings in the module settings and turned them back on again and I still get nothing.  I have been on the Foundry Discord asking people and they don't seem to know why I can't get the menu to pull up either.  Any Ideas?

**Comment by Moerill** [comment]
i do not really understand the problem. Partially because there is no mention of right clicking in the part of the documentation you linked.

Are you not able to create templates at all when using a spell? (That is a base 5e feature and more of a question for the dnd5e part of the FVTT discord)
Or are you not able to set a template for a specific spell? (That one is an input field in the spells/abilities/items sheet)
Or am i completly off?

Also.. its nice that you reinstall the module, but the more important part is that you disable all other modules.

**Comment by Deathtone3** [comment]
I'm not able to set templates for specific spells.  I have deactivated all modules except for MESS and it still doesn't work.  I just assumed you right click based on this image from the documentation. 
https://github.com/Moerill/Mess/blob/master/img/auto_template.gif

Maybe I'm just doing it wrong

**Comment by Moerill** [comment]
So the dialog is not opening for you when you're trying to use a spell with an AoE range?
(Try dragging fireball into your character and use that one to test this)
If that doesn't work (even without mess) then you got some basic dnd problem and i'd suggest you go over to the dnd5e part of the FVTT discord.

**Comment by Deathtone3** [comment]
Okay that works so it only works with spells that are preset with AOE effects I can't just adjust a spell to have an AOE effect then?

**Comment by Moerill** [comment]
Seems like you need to take a closer look at how the 5e system works.
It does work for every spell (and i think feature) that base dnd 5e would create a template for (which is every that has its, i think, target attribute set to some area.)
